name: kitchen

on:
  push:
    branches: [master, ci]
  pull_request:
    branches: [master]

env:
  CHEF_LICENSE: accept-no-persist
jobs:
  integration:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        os:
          - amazonlinux-2
          - centos-8
          - debian-11
          - fedora-34
          - oraclelinux-8
          - ubuntu-2004
        workstation_version:
          - '21.3.346'
          - '21.11.679'
        suite: [default]
      fail-fast: false
    steps:
    - name: Check out code
      uses: actions/checkout@v2
    - name: Install Chef
      uses: actionshub/chef-install@main
      with:
        version: ${{ matrix.workstation_version }}
    - name: Cookstyle
      run: cookstyle --display-cop-names --extra-details
    - name: Rspec
      run: chef exec rspec
    - name: Test-Kitchen
      uses: actionshub/test-kitchen@main
      with:
        suite: ${{ matrix.suite }}
        os: ${{ matrix.os }}
      env:
        KITCHEN_LOCAL_YAML: kitchen.dokken.yml
